### ISSUE TITLE
REQUEST: please share the wf!

### ISSUE THREAD

**Issue by agawrylak** [shiimizu/ComfyUI-PhotoMaker-Plus#3]
I've had okay results with conditioning concat, combine does nothing, average is bad.

**Comment by agawrylak** [comment]
![image](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/64438253/9efe0625-1c29-4421-9575-5f23a570161c)
wf should be encoded

**Comment by klinter007** [comment]
i didnt see a workflow in your image, but i share the same feeling.
i tried doing the same as the suggested workflow on the git, but feels like there's something missing.

**Comment by shiimizu** [comment]
I updated the Readme with a proper workflow. You may try using that as a base.

**Comment by klinter007** [comment]
Mizu thank you for putting the time for it.
I'm sorry but this is very unclear on how to use it  - i actually did not get anything even similar to my images.
<img width="415" alt="image" src="https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/131816305/d55e74b0-e8ec-41f2-b279-4a367d82348e">

also, this version of the git says nothing about the lora, yet you load it in the new workflow you share.

please accept this as constructive criticism - I appreciate you putting the time and effort in building something and releasing to the community, but we need some more communication. thanks.

**Comment by agawrylak** [comment]
lora is the model, download it from huggingface

also for me your wf does not work at all

**Comment by klinter007** [comment]
[workflow (9).json](https://github.com/shiimizu/ComfyUI-PhotoMaker/files/13982113/workflow.9.json)

**Comment by agawrylak** [comment]
@klinter007 this one works for you?

**Comment by shiimizu** [comment]
> also, this version of the git says nothing about the lora, yet you load it in the new workflow you share.
> 
> please accept this as constructive criticism - I appreciate you putting the time and effort in building something and releasing to the community, but we need some more communication. thanks.

`photomaker-v1.bin` contains a CLIP Vision model and a LoRa. It should show up in the Lora Loader node and load the correct weights automatically. I had to make it like this because users didn't want to manually extract the LoRa inside. So you only need to download **one** file: [photomaker-v1.bin](https://huggingface.co/TencentARC/PhotoMaker/blob/main/photomaker-v1.bin) and place it in a `photomaker` directory in the `models` directory.

Ideally, the `trigger_word` should be placed right after the subject, in this case `man` or `woman`, because it will repeat those tokens by the number of images supplied. In your case now: `handsome man img wearing glasses,`. Before, it was repeating the comma `,` token.

**Comment by shiimizu** [comment]
> also, this version of the git says nothing about the lora, yet you load it in the new workflow you share.
> 
> please accept this as constructive criticism - I appreciate you putting the time and effort in building something and releasing to the community, but we need some more communication. thanks.

`photomaker-v1.bin` contains a CLIP Vision model and a LoRa. It should show up in the Lora Loader node and load the correct weights automatically. I had to make it like this because users didn't want to manually extract the LoRa inside. So you only need to download **one** file: [photomaker-v1.bin](https://huggingface.co/TencentARC/PhotoMaker/blob/main/photomaker-v1.bin) and place it in a `photomaker` directory in the `models` directory. You can delete the previous lora file that you made.

Ideally, the `trigger_word` should be placed right after the subject, in this case `man` or `woman`, because it will repeat those tokens by the number of images supplied. In your case now: `handsome man img wearing glasses,`. Before, it was repeating the comma `,` token.

**Comment by shiimizu** [comment]
> also, this version of the git says nothing about the lora, yet you load it in the new workflow you share.
> 
> please accept this as constructive criticism - I appreciate you putting the time and effort in building something and releasing to the community, but we need some more communication. thanks.

`photomaker-v1.bin` contains a CLIP Vision model and a LoRa. It should show up in the Lora Loader node and load the correct weights automatically. I had to change it like this because users didn't want to manually extract the LoRa inside. So you only need to download **one** file: [photomaker-v1.bin](https://huggingface.co/TencentARC/PhotoMaker/blob/main/photomaker-v1.bin) and place it in a `photomaker` directory in the `models` directory. You can delete the previous lora file that you made.

Ideally, the `trigger_word` should be placed right after the subject, in this case `man` or `woman`, because it will repeat those tokens by the number of images supplied. In your case now: `handsome man img wearing glasses,`. Before, it was repeating the comma `,` token.

**Comment by agawrylak** [comment]
unfortunately does not seem to work for me at all with the wf provided in description

**Comment by jesenzhang** [comment]
Don't work!
![image](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/7984556/eceb45ec-56b8-4211-a8f5-1384700dada6)

**Comment by LubuLubu2** [comment]
Yeah mine doesn't work either, it generates whatever in the prompt and ignores the image i gave it, both with JugXL and Realvision xl with .7 or 1 lora wight.

**Comment by shiimizu** [comment]
Please try with and without the `trigger_word`. If the final image changes, then that means it's working. If you're generating a man with a woman's profile picture, you will get what she would look like if she were a man.

**Comment by shiimizu** [comment]
The diffusers implementation only accepts 77 tokens and truncates anything longer than that. ComfyUI and SD-WebUI can exceed that limit. I’ve added support for stating the trigger_words multiple times, so maybe you can try that if your prompt gets long.

**Comment by bmaltais** [comment]
Here is a side by side comp:

![image](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/7474674/28f70c89-d1ab-4d99-b3ff-bcb02f9e6a9c)

As you can see, somehow, the non diffuser likeness is very low... I am using the same CKPT as the diffuser version in this example...

**Comment by bmaltais** [comment]
I tried using the exact model from the same huggingface account and it is even worst...

![workflow (1)](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/7474674/52152188-4f76-46aa-9d2d-8fd69a08d294)

**Comment by bmaltais** [comment]
OK... I think I found the issue... Here is the results if I use a file path to images of her instead of passing an image input:

![workflow (2)](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/7474674/4faeca13-9eca-4dc7-85c3-39e6a9d1a4a0)

Likeness via your ComfyUI node is on par... so I suspect an issue with how the node is processing input images...

**Comment by shiimizu** [comment]
That's the `Style strength ratio` feature which is basically using the original conditioning (without PhotoMaker) for the first `n` steps, and then switching to the PhotoMaker conditioning for the rest of the steps. You can replicate this behaviour in ComfyUI using 2 Advanced KSamplers.

![workflow (4)](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/54494639/50b2bd87-4cf5-4e36-ba96-dea1c3f9648d)

**Comment by bmaltais** [comment]
This is awesome... so there is a bit more from a workflow to get similar results to the diffuser version... I will create a workflow node combining the two ksampler to "emulate" the diffusaer sampler... nice

![workflow (3)](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/7474674/996dc7ae-47dd-4a50-9503-3e6b54db7d75)

**Comment by drphero** [comment]
So this doesn't work with the regular loadimage node? But the README workflow shows that should work.

**Comment by agawrylak** [comment]
for me it also only works when giving dir, so we must be doing something wrong

**Comment by bmaltais** [comment]
> for me it also only works when giving dir, so we must be doing something wrong

Indeed… not sure why… maybe the node expect the image to be in a specific resolution, format and since we are no passing that is silently fail?

**Comment by LubuLubu2** [comment]
Yep, i used image path and it worked. quality is not on pair with IPAdapter tho, the image it creates is not as accurate to the images i feed it.

**Comment by hben35096** [comment]
Same problem, only works after filling in the image path, and it doesn't work as well as IPAdapter.
Compared to the official version, this plugin has too few options.

**Comment by bmaltais** [comment]
> Same problem, only works after filling in the image path, and it doesn't work as well as IPAdapter. Compared to the official version, this plugin has too few options.

Compared to the diffuser version it can produce the exact same result but with a much more complex workflow, but it can be done. I also have issue with the direct image now working. Hopefully this can be addressed… or I might just dive in the node code and fix it myself… and create a PR to merge it to main.

**Comment by hben35096** [comment]
![image](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/139383150/158980b3-f666-4046-8232-8d2b938566a6)

This is the effect of FaceID

**Comment by LubuLubu2** [comment]
Thank you.
New update and workflow works even with load image. 
I don't know what style strength ratio is but both produce the same image and both of them are less accurate than what the first sampler generates.

**Comment by hben35096** [comment]
![image](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/139383150/c886e46e-c3dd-4bf3-b34e-147813d80dfe)

Thanks, it worked~

**Comment by danzakuo** [comment]
![workflow_photomaker(shiimizu)](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/123797257/648c4288-9061-4348-831e-98bede4473c9)
Thanks @bmaltais & @hben35096. Finally, the face looks the same as in the photomaker demo.

**Comment by jesenzhang** [comment]
@shiimizu Would you make a ComfyUI reference implementation for InstanceID?

**Comment by shiimizu** [comment]
@jesenzhang https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/issues/15#issuecomment-1906861379

**Comment by jesenzhang** [comment]
> @jesenzhang [#15 (comment)](https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/issues/15#issuecomment-1906861379)

Got it,thx.

**Comment by lyuzhichao** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
tianlongzu, @somerandomguylearningcode, @svegan, @Sitebase, @tengfeiwang1, @Stifler131, @SylveHenry, @0xthoth, @DocBRob, @IIllIIllII, @cyntax-js, @haxpor, @ktakdev, @Times125, @minhluan96, @blank1u, @motolese, @devosend, @mbeasier, @frederic8

**Comment by Times125** [comment]
您好，我已经收到您的来信，会尽快处理。

**Comment by lyuzhichao** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
scsfwgy, @ww4tson, @johndavemanuel, @cybert1t1, @almohajer, @moumc, @4825vinay, @narayu4, @kris79du62, @ccloverx, @dinhnhat0401, @KCChiefsLIV, @kuyhii, @lequochung19971, @wasdseok, @sydneymilligan, @stayrar3, @Necmttn, @cupid4, @zwjtheone

**Comment by ChrisBuckets** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hallstain, @Aosiepcs, @runifgg, @camhoot, @woidzero, @mikeliuu, @MissinA, @cs-joy, @arzel, @aviland, @ysnbogt, @jakubsgit, @krittin-58, @cristoffersantoro, @2h311, @zhaozha, @owieth, @linthan, @BADjelly, @c0mput3rxz, @seropaski, @JiuBanA1, @JefferyCrypto, @Gezegorz1, @PabloPap, @ai376928387, @Net-bo, @rndy28, @ducga1998, @MatteoLeonesi, @uinwxs, @johnyleebrown, @tz792322620, @nguyenthuongvo, @jarz76, @noocool, @markkj, @neiwubao, @hmd7ai, @JinDotCom, @Sajjaddi, @davidluogj, @Hawk1515, @drakulovski, @kithf, @Anubhavjain786, @Snowpine, @Jess21-crtl, @suttapak, @dearyangyu

**Comment by factoryfactory** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hohoc, @ForumPlayer, @IgorFrolov, @proggR, @afatshiba, @bagiyal, @Irvise, @RicoToothless, @ryosua, @ssteiger, @Jmchin, @marti1339, @dillchen, @mrhyperbit, @nakeiven, @seipy, @NOXlocks, @lazzarello, @vitvly, @asing177, @ethantran, @sengthaite, @Margen67, @ggsonic, @ldwformat, @broerjuang, @oblank, @seb-zhu, @wl-tsui, @liangsuifengc, @anonymous2100, @MawiraIke, @wowmarcomei, @wuwenjie1992, @coocro, @chadsr, @ErfanTagh, @flyingmate, @vlad-saling, @gauravssnl, @azerbelhedi, @ochi51, @hjn1023, @NikitaKoren, @i-am-tim, @zhuantouer, @0zguner, @chaschev, @albmin, @tiancheng91

**Comment by shiimizu** [comment]
Workflows are available at https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/tree/main/examples

**Comment by Times125** [comment]
您好，我已经收到您的来信，会尽快处理。

**Comment by ccloverx** [comment]
谢谢，你的邮件我已经收到，我会尽快阅读并给与回复
